services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:cached
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/:cached
    container_name: project_nginx
    depends_on:
      - app
  app:
    user: "1000:1000"
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - "./:/var/www:cached"
    container_name: project_main
    depends_on:
      - db
  db:
    image: postgis/postgis:17-3.4
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ru_RU"
    volumes:
      - "./tmp/database:/var/lib/postgresql/data:cached"
    container_name: project_db

